sonar.projectKey=urbanops-frontend
sonar.projectName=UrbanOps Frontend
sonar.projectVersion=1.0
sonar.sources=app,components,lib
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.ts,__tests__/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=.next/**,node_modules/**,coverage/**,next-env.d.ts
sonar.coverage.exclusions=app/**,components/layout/**,components/dashboard/**,components/home/**,components/landing/**,components/admin/**,components/map/**,components/shared/MapView.tsx,components/shared/SignalerModal.tsx,components/shared/PageBackdrop.tsx,components/ui/dialog.tsx,lib/mockData.ts,lib/types.ts
